version: '3.7'
services:

  terraform:
    image: hashicorp/terraform:1.1.9
    env_file: .env
    volumes:
      - '~/.aws:/root/.aws:ro'
      - '.:/app'
    working_dir: '/app'

  envvars:
    image: 'flemay/envvars'
    env_file: .env
    working_dir: '/app'
    volumes:
      - '.:/app'
